/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class gameOverUI extends Laya.Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":750,"height":1334},"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(gameOverUI.uiView);
        }
    }
    REG("ui.gameOverUI",gameOverUI);
    export class gameStartUI extends Laya.Scene {
		public begin:Laya.Sprite;
		public intro:Laya.Sprite;
		public ranking:Laya.Sprite;
        public static  uiView:any ={"type":"Scene","props":{"width":750,"runtime":"script/GameStart.ts","height":1334,"autoDestroyAtClosed":false},"compId":2,"child":[{"type":"Rect","props":{"y":1136,"x":0,"width":750,"lineWidth":1,"height":198,"fillColor":"#f4f6fa"},"compId":15},{"type":"Sprite","props":{"y":914,"x":255,"var":"begin","texture":"gamestart/begin.png"},"compId":16},{"type":"Sprite","props":{"y":1149,"x":449,"width":115,"var":"intro","texture":"gamestart/intro.png","height":115},"compId":17},{"type":"Sprite","props":{"y":1149,"x":172,"width":115,"var":"ranking","texture":"gamestart/ranking.png","height":115},"compId":18},{"type":"Sprite","props":{"y":1274,"x":437,"width":139,"texture":"gamestart/intro-text.png","height":33},"compId":20},{"type":"Sprite","props":{"y":1274,"x":176,"width":111,"texture":"gamestart/ranking-text.png","height":33},"compId":21},{"type":"Sprite","props":{"y":387,"x":209.5,"texture":"gamestart/title.png"},"compId":22}],"loadList":["gamestart/begin.png","gamestart/intro.png","gamestart/ranking.png","gamestart/intro-text.png","gamestart/ranking-text.png","gamestart/title.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(gameStartUI.uiView);
        }
    }
    REG("ui.gameStartUI",gameStartUI);
    export class gameViewUI extends Laya.Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":750,"height":1334},"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(gameViewUI.uiView);
        }
    }
    REG("ui.gameViewUI",gameViewUI);
}